# Workflow to minimize the reken.js file.

name: Minimize Reken

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: 'src'
          output: 'dist'

      # gzips files in the dist directory
      - name: CompressFiles
        uses: ThiagoJaweb/ghaction-CompressFiles@v1.0.3
        with:
          path: 'dist'
          extensions: '.js,.css,.html'
          tools: 'brotli,gzip'
          
      # Generate readme.html from readme.md
      - name: Convert Markdown to HTML
        uses: natescherer/markdown-to-html-with-github-style-action@v1.1.0
        with:
          #path: README.md,CHANGELOG.md,docs\doc1.md
          path: README.md,documentation/developer-guide/toc.md,documentation/developer-guide/chapter-1.md,documentation/developer-guide/chapter-2.md,documentation/developer-guide/chapter-3.md,documentation/developer-guide/chapter-4.md,documentation/developer-guide/chapter-5.md,documentation/developer-guide/chapter-6.md,documentation/developer-guide/chapter-7.md,documentation/developer-guide/chapter-8.md,documentation/developer-guide/chapter-9.md,documentation/developer-guide/chapter-10.md,documentation/developer-guide/chapter-11.md,documentation/developer-guide/chapter-12.md,documentation/developer-guide/chapter-13.md,documentation/developer-guide/chapter-14.md
          outputpath: dist
          matchpathstructure: true

      # Copy documentation pictures
      - name: Copy documentation images
        run: |
          mkdir dist/documentation/developer-guide/img
          cp documentation/developer-guide/img/*.jpg dist/documentation/developer-guide/img

      # Auto commits minified files to the repository
      # Ignore it if you don't want to commit the files to the repository 
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: 'dist'
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
